### ISSUE TITLE
Why use MutableLivedata and Livedata together

### ISSUE THREAD

**Issue by alvaroDigio** [antoniolg/architect-coders#1]
This is really good example to learn livedata + coroutines, but I have a question. 
```
private val _model = MutableLiveData<UiModel>()
val model: LiveData<UiModel>
        get() {
            if (_model.value == null) findMovie()
            return _model
        }
```

Why use to variables `model` and `_model`? What is the advantages with this replication? It's not enough with `_model` as MutableLiveData?

**Comment by antoniolg** [comment]
This way, you don't allow other modules in your app to mutate the value of the LiveData, only de ViewModel can do it. It's just because of that, so if you don't feel that threat, you can omit it 😄
